#!/bin/sh

DIR=$(dirname $(readlink -f $0))
CLEAN=${CLEAN:-0}

[ $CLEAN -eq 1 ] && rm -rf $DIR/.build

docker run --rm -i \
    -u $(id -u):$(id -g) \
    -v $DIR:$DIR:rw \
    mstorsjo/llvm-mingw:20220323 <<EOF

[ -d $DIR/.build ] || (
    mkdir -p $DIR/.build
    cd $DIR/.build
    cmake -G Ninja \
        -DCMAKE_TOOLCHAIN_FILE=$DIR/x86_64-w64-mingw32.cmake \
        -DCMAKE_BUILD_TYPE=Release \
        $DIR
)

cmake --build $DIR/.build

EOF
